#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=20gb,walltime=0:30:00
#PBS -N app-synthstrip

set -ex
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:7.3.2 ./synthstrip.sh
