#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=20gb,walltime=0:30:00
#PBS -N app-synthstrip

set -ex
[ ! -f nodif.nii.gz ] && time singularity exec -e docker://brainlife/fsl:5.0.11 ./select_nodif.sh
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:7.3.2 ./synthstrip.sh
